USE LABORATORY;

-- Create donors table
CREATE TABLE DONORS (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(200) NOT NULL,
    address VARCHAR(255),
    blood_group VARCHAR(3) NOT NULL CHECK (BLOOD_GROUP REGEXP '^(A|B|AB|O)[+-]$'),
    phone VARCHAR(15) NOT NULL CHECK (PHONE REGEXP '^[+]?[0-9]{10,15}$'),
    profilePicture VARCHAR(300),
    created_by INT UNSIGNED NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    FOREIGN KEY (created_by) REFERENCES LABEMPLOYEE(ID) ON DELETE CASCADE
);

USE LABORATORY;

-- Create labEmployee table
CREATE TABLE LABEMPLOYEE (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(200) NOT NULL,
    ADDRESS VARCHAR(255),
    BLOOD_GROUP VARCHAR(3) NOT NULL CHECK (BLOOD_GROUP REGEXP '^(A|B|AB|O)[+-]$'),
    PHONE VARCHAR(15) NOT NULL CHECK (PHONE REGEXP '^[+]?[0-9]{10,15}$'),
    PROFILEPICTURE VARCHAR(300),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

USE laboratory;

-- Create donations table
CREATE TABLE DONATIONS (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DONATION_DATE DATE NOT NULL,
    DONATION_PLACE VARCHAR(255) NOT NULL,
    BLOOD_GROUP VARCHAR(3) CHECK (BLOOD_GROUP REGEXP '^(A|B|AB|O)[+-]$'),
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    DONATION_IMAGE VARCHAR(2000),
    CREATED_BY INT UNSIGNED NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CREATED_BY) REFERENCES LABEMPLOYEE(ID) ON DELETE CASCADE
);

USE laboratory;

-- Create comments table
CREATE TABLE COMMENTS (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DONOR_ID INT UNSIGNED NOT NULL,
    DONATION_ID INT UNSIGNED,
    PROFILEPICTURE VARCHAR(300),
    NAME VARCHAR(100) NOT NULL,
    COMMENT TEXT,
    RATING TINYINT UNSIGNED CHECK (RATING >= 0 AND RATING <= 5),
    IS_GENERAL TINYINT(1) DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (DONOR_ID) REFERENCES DONORS(ID) ON DELETE CASCADE,
    FOREIGN KEY (DONATION_ID) REFERENCES DONATIONS(ID) ON DELETE CASCADE
);

USE laboratory;

-- Create donation_records table
CREATE TABLE DONATION_RECORDS (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DONOR_ID INT UNSIGNED NOT NULL,
    DONATION_ID INT UNSIGNED NOT NULL,
    BLOOD_GROUP VARCHAR(3) NOT NULL CHECK (BLOOD_GROUP REGEXP '^(A|B|AB|O)[+-]$'),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (DONOR_ID) REFERENCES DONORS(ID) ON DELETE CASCADE,
    FOREIGN KEY (DONATION_ID) REFERENCES DONATIONS(ID) ON DELETE CASCADE
);