
USE laboratory;

-- Create comments table
CREATE TABLE COMMENTS (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DONOR_ID INT UNSIGNED NOT NULL,
    DONATION_ID INT UNSIGNED,
    PROFILEPICTURE VARCHAR(300),
    NAME VARCHAR(100) NOT NULL,
    COMMENT TEXT,
    RATING TINYINT UNSIGNED CHECK (RATING >= 0 AND RATING <= 5),
    IS_GENERAL TINYINT(1) DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (DONOR_ID) REFERENCES DONORS(ID) ON DELETE CASCADE,
    FOREIGN KEY (DONATION_ID) REFERENCES DONATIONS(ID) ON DELETE CASCADE
);
