USE laboratory;

-- Create donations table
CREATE TABLE DONATIONS (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DONATION_DATE DATE NOT NULL,
    DONATION_PLACE VARCHAR(255) NOT NULL,
    BLOOD_GROUP VARCHAR(3) CHECK (BLOOD_GROUP REGEXP '^(A|B|AB|O)[+-]$'),
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    DONATION_IMAGE VARCHAR(2000),
    CREATED_BY INT UNSIGNED NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CREATED_BY) REFERENCES LABEMPLOYEE(ID) ON DELETE CASCADE
);
