

USE laboratory;

-- Create donation_records table
CREATE TABLE DONATION_RECORDS (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DONOR_ID INT UNSIGNED NOT NULL,
    DONATION_ID INT UNSIGNED NOT NULL,
    BLOOD_GROUP VARCHAR(3) NOT NULL CHECK (BLOOD_GROUP REGEXP '^(A|B|AB|O)[+-]$'),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (DONOR_ID) REFERENCES DONORS(ID) ON DELETE CASCADE,
    FOREIGN KEY (DONATION_ID) REFERENCES DONATIONS(ID) ON DELETE CASCADE
);