USE LABORATORY;

-- Create donors table
CREATE TABLE donors (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(2000) NOT NULL,
    address VARCHAR(255),
    blood_group VARCHAR(3) NOT NULL CHECK (blood_group REGEXP '^(A|B|AB|O)[+-]$'),
    phone VARCHAR(15) CHECK (phone REGEXP '^[+]?[0-9]{10,15}$'),
    profilePicture VARCHAR(300),
    role VARCHAR(20) NOT NULL DEFAULT 'donor',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
