USE LABORATORY;

-- Create donors table
CREATE TABLE DONORS (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(200) NOT NULL,
    address VARCHAR(255),
    blood_group VARCHAR(3) NOT NULL CHECK (BLOOD_GROUP REGEXP '^(A|B|AB|O)[+-]$'),
    phone VARCHAR(15) NOT NULL CHECK (PHONE REGEXP '^[+]?[0-9]{10,15}$'),
    profilePicture VARCHAR(300),
    created_by INT UNSIGNED NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    FOREIGN KEY (created_by) REFERENCES LABEMPLOYEE(ID) ON DELETE CASCADE
);
