USE LABORATORY;

-- Create labEmployee table
CREATE TABLE LABEMPLOYEE (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(200) NOT NULL,
    ADDRESS VARCHAR(255),
    BLOOD_GROUP VARCHAR(3) NOT NULL CHECK (BLOOD_GROUP REGEXP '^(A|B|AB|O)[+-]$'),
    PHONE VARCHAR(15) NOT NULL CHECK (PHONE REGEXP '^[+]?[0-9]{10,15}$'),
    PROFILEPICTURE VARCHAR(300),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
